# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
  
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Pacaking 
    pool:
      vmImage: ubuntu-latest
    jobs:
    - job: Job_1
      displayName: code_clone_scan
      steps:
      - script: echo Cloning the repo
        displayName: 'Run a one-line script'
      - checkout: self
        fetchDepth: 1
      - script: echo Scanning the code
      - task: UsePythonVersion@0  # Select Python version
        inputs:
          versionSpec: '3.x'
        displayName: 'Use Python 3.x'

      - script: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate
          pip install -r requirements.txt
        displayName: 'Install Python dependencies'

      - script: |
          wget -O sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin
        displayName: 'Install SonarScanner CLI'

      - script: |
          sonar-scanner \
          -Dsonar.projectKey=tg-vishwa-aug24 \
          -Dsonar.organization=tg-vishwa-aug24 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$(SONAR_TOKEN) \
          -Dsonar.python.version=3.x  # Replace with the Python version you use
        displayName: 'Run SonarScanner CLI'
        env:
          SONAR_TOKEN: $(SONAR_TOKEN)
